# Scheduler test configuration - tests different scheduler types
%YAML 1.2
---
application:
  title: Streaming Client Scheduler Test
  version: 1.0
  log_level: INFO

data_logging: false
source: "replayer"

replayer:
  basename: "surgical_video"
  frame_rate: 30
  repeat: false
  realtime: false
  count: 3  # Minimal frames for scheduler test

# Format converter for replayer (matches endoscopy_tool_tracking format)
format_converter_replayer:
  out_tensor_name: source_video
  out_dtype: "float32"
  scale_min: 0.0
  scale_max: 255.0

format_converter:
  in_dtype: "rgba8888"
  out_dtype: "rgb888"
  out_tensor_name: tensor

streaming_client:
  width: 640
  height: 480
  fps: 30
  server_ip: "127.0.0.1"
  signaling_port: 48010
  receive_frames: false
  send_frames: false

visualize_frames: false

# This will be overridden by test parameter
scheduler: "default"

# Scheduler configurations
multi_thread_scheduler:
  worker_thread_number: 2
  stop_on_deadlock: true
  stop_on_deadlock_timeout: 5000

event_based_scheduler:
  stop_on_deadlock: true
  stop_on_deadlock_timeout: 5000

greedy_scheduler:
  max_duration_ms: 5000

tracking: false
