# Logging test configuration - tests graceful handling of file access issues
%YAML 1.2
---
application:
  title: Streaming Client Logging Test
  version: 1.0
  log_level: INFO

data_logging: false

# Use V4L2 source (handles missing camera gracefully)
source: "v4l2"

# V4L2 configuration (will gracefully handle missing camera)
v4l2:
  device: "/dev/video10"  # Non-existent device for testing
  width: 640
  height: 480
  fps: 30

# Format converter
format_converter:
  in_dtype: "rgba8888"
  out_dtype: "rgb888"
  out_tensor_name: tensor

# Streaming client - minimal configuration
streaming_client:
  width: 640
  height: 480
  fps: 30
  server_ip: "127.0.0.1"
  signaling_port: 48010
  receive_frames: false
  send_frames: false

# Disable visualization for faster testing
visualize_frames: false

# Use default scheduler
scheduler: "default"

# Disable tracking for performance
tracking: false
