# Basic functional test configuration - minimal settings
%YAML 1.2
---
application:
  title: Streaming Client Basic Test
  version: 1.0
  log_level: INFO

# Disable data logging for faster test execution
data_logging: false

# Use replayer source (no camera required)
source: "replayer"

# Video replayer configuration - use test data (matches endoscopy_tool_tracking format)
replayer:
  basename: "surgical_video"
  frame_rate: 30
  repeat: false
  realtime: false
  count: 5  # Only process 5 frames for fast test

# Format converter for replayer (matches endoscopy_tool_tracking format)
format_converter_replayer:
  out_tensor_name: source_video
  out_dtype: "float32"
  scale_min: 0.0
  scale_max: 255.0

# Format converter - basic RGB conversion  
format_converter:
  in_dtype: "rgba8888"
  out_dtype: "rgb888"
  out_tensor_name: tensor
  scale_min: 0.0
  scale_max: 255.0

# Streaming client - minimal configuration
streaming_client:
  width: 640
  height: 480
  fps: 30
  server_ip: "127.0.0.1"
  signaling_port: 48010
  receive_frames: false  # Don't try to connect to server
  send_frames: false     # Don't try to send frames

# Disable visualization for faster testing
visualize_frames: false

# Use default scheduler
scheduler: "default"

# Disable tracking for performance
tracking: false
