[build-system]
requires = ["scikit-build-core>=0.10"]
build-backend = "scikit_build_core.build"

[project]
name = "holoscan-connext-dds"
version = "1.0.0"
description = "Generic RTI Connext DDS operators for Holoscan"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10"
dependencies = [
    "holoscan-cu13>=4.5.0",
    "rti.connext==7.7.0",
]

[tool.scikit-build]
cmake.version = ">=3.20"
cmake.source-dir = "../.."
cmake.build-type = "Release"
cmake.args = [
    "-DBUILD_ALL=OFF",
    "-DMODULE_holoscan_connext_dds=ON",
    "-DHOLOHUB_BUILD_PYTHON=ON",
    "-DBUILD_TESTING=OFF",
]
wheel.packages = []
