extensions:
  - lib/gxf_extensions/libgxf_tapnext_inference.so

replayer:
  basename: "colonoscope_0001_short"
  frame_rate: 30
  repeat: false
  realtime: false
  count: 0

window:
  window_size: 20
  overlap_size: 10
  grid_size: 15

preprocessor_3d:
  calibration_matrix: "[[227.60416, 0, 237.5], [0, 227.60416, 237.5], [0, 0, 1]]"

holoviz:
  width: 480
  height: 848
  tensors:
    - name: "frame"
      type: color
      priority: 0

holoviz_3d:
  width: 1280
  height: 720

preprocessor:
  out_tensor_name: source_video
  out_dtype: "float32"
  scale_min: -1.0
  scale_max: 1.0
  resize_height: 256
  resize_width: 256


tapnext:
  model_file_path_init: models/tapnext_init.bf16.engine
  model_file_path_fwd: models/tapnext_forward.bf16.engine
  engine_cache_dir: engines

  # Tensor names from config
  input_tensor_names_init: ["video", "query_points"]
  input_binding_names_init: ["video", "query_points"]
  output_tensor_names_init: ["tracks", "track_logits", "visible_tracks", "step", "rg_lru_state", "conv1d_state"]
  output_binding_names_init: ["tracks", "track_logits", "visible_logits", "step", "rg_lru_state", "conv1d_state"]

  input_tensor_names_fwd: ["video", "query_points", "step", "rg_lru_state", "conv1d_state"]
  input_binding_names_fwd: ["video", "query_points", "step", "rg_lru_state", "conv1d_state"]
  output_tensor_names_fwd: ["tracks", "track_logits", "visible_tracks", "step", "rg_lru_state", "conv1d_state"]
  output_binding_names_fwd: ["tracks", "track_logits", "visible_logits", "step_1", "rg_lru_state_1", "conv1d_state_1"]

  # State tensors that are preserved
  state_tensor_names: ["step", "rg_lru_state", "conv1d_state"]

  grid_size: 15
  grid_height: 256
  grid_width: 256

  # Additional params
  max_batch_size: 1
  enable_fp16: False # Set based on model precision if needed
  verbose: False


tracks_4d:
  backend: trt
  model_file: models/tracksto4d.bf16.engine # models/tracks_to_4d.bf16.engine
  is_engine_path: true
  inference_map:
    "tracks_4d": ["focal_params","projections2","projections2_static","rotation_params","position_params",
      "B",
      "points3D",
      "points3D_static",
      "depths",
      "depths_static",
      "unused1",
      "basis_params",
      "unused2",
      "unused3",
      "points3D_camera",
      "NR"]
  pre_processor_map:
    "tracks_4d": ["tracks"]
  in_tensor_names: ["tracks"]
  out_tensor_names: [
    "focal_params",
    "projections2",
    "projections2_static",
    "rotation_params",
    "position_params",
    "B",
    "points3D",
    "points3D_static",
    "depths",
    "depths_static",
    "unused1",
    "basis_params",
    "unused2",
    "unused3",
    "points3D_camera",
    "NR"]
