%YAML 1.2
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
extensions:
  - libgxf_std.so
  - libgxf_cuda.so
  - libgxf_multimedia.so
  - libgxf_serialization.so
  - libgxf_stream_playback.so

source: "replayer" # or "aja"

replayer:  # VideoStreamReplayer
  basename: "surgical_video"
  frame_rate: 0 # as specified in timestamps
  repeat: true # default: false
  realtime: false # default: true
  count: 0 # default: 0 (no frame count restriction)

aja:  # AJASourceOp
  width: 1920
  height: 1080
  rdma: true
  enable_overlay: false

detection_preprocessor:  # FormatConverter
    out_tensor_name: source_video_pre
    out_dtype: "float32"
    resize_width: 300
    resize_height: 300
    scale_min: -1.0
    scale_max: 1.0

segmentation_preprocessor:  # FormatConverter
  out_tensor_name: endo_preprocessed
  out_dtype: "float32"
  resize_width: 736
  resize_height: 480

inference:  # InferenceOp
  backend: "trt"
  pre_processor_map: 
    "ssd": ["source_video_pre"]
    "tool_seg": ["endo_preprocessed"]
  inference_map: 
    "ssd": ["inference_output_num_detections", 
            "inference_output_detection_boxes", 
            "inference_output_detection_scores", 
            "inference_output_detection_classes",]
    "tool_seg": ["tool_seg_inferred"]
  enable_fp16: true

segmentation_postprocessor:  # SegmentationPostprocessorOp
  in_tensor_name: tool_seg_inferred
  network_output_type: softmax
  data_format: nchw

detection_postprocessor:  # DetectionPostprocessorOp
  scores_threshold: 0.5
  label_names: ["Grasper", 
                "Bipolar", 
                "Hook", 
                "Scissors", 
                "Clipper", 
                "Irrigator", 
                "Spec.Bag"]

holoviz:  # Holoviz
  color_lut: [
    [0.65, 0.81, 0.89, 0.1],
    [0.2, 0.63, 0.17, 0.7],
    [0.98, 0.6, 0.6, 0.7],
    [0.89, 0.1, 0.11, 0.7],
    [0.99, 0.75, 0.44, 0.7],
    [1.0, 0.5, 0.0, 0.7],
    [0.0, 0.0, 0.0, 0.1]
    ]  
  tensors:
    - name: ""
      type: color
    - name: "out_tensor"
      type: color_lut
    - name: Grasper_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [1.0, 0.0, 1.0, 1.0]
    - name: Grasper_label
      type: text
      text: ["Grasper"]
      opacity: 0.7
      color: [1.0, 0.0, 1.0, 1.0]      
    - name: Bipolar_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [0.0, 1.0, 0.0, 1.0]
    - name: Bipolar_label
      type: text
      text: ["Bipolar"]
      opacity: 0.7
      color: [0.0, 1.0, 0.0, 1.0]
    - name: Hook_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [1.0, 1.0, 1.0, 1.0]
    - name: Hook_label
      type: text
      text: ["Hook"]
      opacity: 0.7
      color: [1.0, 1.0, 1.0, 1.0]            
    - name: Scissors_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [0.0, 1.0, 1.0, 1.0]
    - name: Scissors_label
      type: text
      text: ["Scissors"]
      opacity: 0.7
      color: [0.0, 1.0, 1.0, 1.0]            
    - name: Clipper_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [1.0, 0.5, 0.0, 1.0]
    - name: Clipper_label
      type: text
      text: ["Clipper"]
      opacity: 0.7
      color: [1.0, 0.5, 0.0, 1.0]          
    - name: Irrigator_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [0.5, 0.5, 0.5, 1.0]
    - name: Irrigator_label
      type: text
      text: ["Irrigator"]
      opacity: 0.7
      color: [0.5, 0.5, 0.5, 1.0]            
    - name: Spec.Bag_rectangle
      type: rectangles
      opacity: 0.7
      line_width: 4
      color: [1.0, 1.0, 0.0, 1.0]
    - name: Spec.Bag_label
      type: text
      text: ["Spec.Bag"]
      opacity: 0.7
      color: [1.0, 1.0, 0.0, 1.0]
