# SPDX-FileCopyrightText: Copyright (c) {% now 'utc', '%Y' %} {{ cookiecutter.full_name }}{% if cookiecutter.affiliation %} / {{ cookiecutter.affiliation }}{% endif %}. All rights reserved.
# SPDX-License-Identifier: {{ cookiecutter._license }}
{%- set op_class = cookiecutter.operator_slug.split('_')|map('capitalize')|join('') %}

# Re-export each operator from its per-operator subpackage so callers can
# write `from holoscan.{{ cookiecutter.module_slug }} import {{ op_class }}`
# in addition to the longer
# `from holoscan.{{ cookiecutter.module_slug }}.{{ cookiecutter.operator_slug }} import {{ op_class }}`.
#
# The per-operator subpackages and their `__init__.py` are generated by
# pybind11_add_holohub_module (cmake/pybind11_add_holohub_module.cmake) — the
# helper handles ABI error diagnostics there.
from .{{cookiecutter.operator_slug}} import {{ op_class }}

__all__ = ["{{ op_class }}"]
