name: 📚 Documentation
description: Report a documentation issue related to https://nvidia-holoscan.github.io/holohub/
title: '[Docs]: '
labels: ['documentation']
body:
  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue Type
      description: Select all that apply.
      options:
        - label: Typo or grammatical error
        - label: Incorrect or outdated information
        - label: Missing information or incomplete documentation
        - label: Broken link
        - label: Unclear or confusing explanation
        - label: Code example not working
        - label: Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Link to the documentation page with the issue.
      placeholder: 'e.g., https://nvidia-holoscan.github.io/holohub/...'
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: Section/Heading
      description: Which section or heading contains the issue?
      placeholder: 'e.g., Installation Steps'
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the documentation issue. Please report in English.
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How could we improve this? If applicable, provide corrected text or additional information.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add screenshots, related links, or any other context that helps explain the issue.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Thanks for contributing to HoloHub 🎉!

