# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# CMake FetchContent manifest emitter for external Holoscan Module dependencies.
# Consumes ModuleDep records from external_resolver and emits the
# external_operators_manifest.cmake that the HoloHub root CMakeLists.txt includes.

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Iterable

from utilities.cli.external_resolver import ModuleDep


def _provider_id(module_name: str) -> str:
    """Sanitise a module name into a CMake-friendly identifier (FetchContent
    Declare's first arg, used downstream as ${id}_SOURCE_DIR etc.).

    holoscan-example-utils -> holoscan_example_utils
    """
    return re.sub(r"[^A-Za-z0-9_]", "_", module_name)


def write_external_operators_manifest(
    deps: Iterable[ModuleDep],
    output_path: Path,
) -> None:
    """Emit ${build_dir}/external_operators_manifest.cmake — the data-only
    manifest the HoloHub root CMakeLists.txt includes early.

    Contents per declared dep:
      - FetchContent_Declare(<provider_id> GIT_REPOSITORY <url> GIT_TAG <ref>).
        Pure declaration; no fetch.
      - For HOLOHUB_LOCAL_<NAME> overrides: also emit
        FETCHCONTENT_SOURCE_DIR_<UPPER>=<path> so MakeAvailable uses the local
        tree instead of cloning.
      - One set(HOLOHUB_EXT_OP_<op>_PROVIDER <provider_id>) per advertised
        operator (a normal variable, not a cache entry — see below). The
        HoloHub root's post-step iterates these and calls MakeAvailable on
        the modules whose ops ended up ON.

    The manifest is "data only" — no add_subdirectory, no MakeAvailable, no
    add_holohub_operator. CMake decides what to fetch based on which OP_<x>
    survives configure-time gating.

    Provider lookups are NORMAL variables (no `CACHE INTERNAL`), so they
    don't survive across configure runs. This matters when a build dir is
    reused across consumers with different external Module needs (e.g.
    switching between cpp and python builds of the same app): the post-
    step in the root CMakeLists.txt would otherwise find a cached
    PROVIDER lookup whose FetchContent_Declare wasn't issued in the
    current configure, and FetchContent_MakeAvailable would fail with
    "No content details recorded for <provider>". A normal variable
    starts fresh every configure, so each manifest fully describes the
    state of provider lookups for this run."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# SPDX-FileCopyrightText: generated by ./holohub external module resolver.",
        "# Do not edit by hand — re-run the CLI to refresh.",
        "#",
        "# Data-only manifest: external module declarations via holohub_declare_external_module.",
        "# That function (defined in HoloHubConfigHelpers.cmake) handles FetchContent_Declare",
        "# and registers HOLOHUB_EXT_OP_<op>_PROVIDER for each operator. The HoloHub root",
        "# CMakeLists.txt's end-of-file block walks OP_<x>=ON state after subdirectories",
        "# settle and FetchContent_MakeAvailable's only the modules whose operators are enabled.",
        "",
    ]
    seen_op_provider: dict[str, str] = {}
    seen_provider_ids: dict[str, str] = {}

    for dep in deps:
        provider = _provider_id(dep.name)
        if (prior_name := seen_provider_ids.get(provider)) and prior_name != dep.name:
            print(
                f"WARNING: modules '{prior_name}' and '{dep.name}' both map to "
                f"provider ID '{provider}'. The latter will overwrite the former.",
                file=sys.stderr,
            )
        seen_provider_ids[provider] = dep.name
        provider_upper = provider.upper()
        ref_note = f", ref {dep.ref}" if dep.ref else ""
        origin = "local-override" if dep.override_path else "fetch"
        lines.append(f"# {dep.name} ({origin}{ref_note})")

        override_str = None
        if dep.override_path is not None:
            override_str = str(dep.override_path).replace("\\", "/")
            # FETCHCONTENT_SOURCE_DIR_<UPPER> is a cache variable (global scope) that
            # redirects FetchContent_MakeAvailable at the local tree. Emitted as a
            # separate set() before the function call so it's visible to readers.
            lines.append(
                f'set(FETCHCONTENT_SOURCE_DIR_{provider_upper} "{override_str}" '
                f'CACHE PATH "Local override for {dep.name}" FORCE)'
            )

        # Build holohub_declare_external_module(...) call, forwarding FetchContent
        # args directly. PROVIDES_OPERATORS registers HOLOHUB_EXT_OP_<op>_PROVIDER
        # as a normal variable inside the function (PARENT_SCOPE → root CMakeLists.txt
        # directory scope).
        call_parts = [f"holohub_declare_external_module({provider}"]
        if dep.git_url and dep.ref:
            call_parts.append(f'    GIT_REPOSITORY  "{dep.git_url}"')
            call_parts.append(f'    GIT_TAG         "{dep.ref}"')
        elif override_str is not None:
            call_parts.append(f'    SOURCE_DIR  "{override_str}"')

        for op in dep.provides_operators:
            prior = seen_op_provider.get(op)
            if prior and prior != provider:
                print(
                    f"WARNING: operator '{op}' claimed by both '{prior}' and "
                    f"'{provider}'. Latter wins; the first will be ignored.",
                    file=sys.stderr,
                )
            seen_op_provider[op] = provider

        if dep.provides_operators:
            call_parts.append(f"    PROVIDES_OPERATORS {' '.join(dep.provides_operators)}")

        call_parts.append(")")
        lines.append("\n".join(call_parts))
        lines.append("")

    output_path.write_text("\n".join(lines))
