# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Unit test configuration for StreamingClientOp operator
# This is a minimal configuration for testing operator functionality only

%YAML 1.2
---
# Minimal streaming client configuration for unit testing
streaming_client:
  width: 640
  height: 480
  fps: 30
  server_ip: "127.0.0.1"
  signaling_port: 48010
  
  # Disable network operations for unit testing
  send_frames: false
  receive_frames: false
  
  # Minimal validation thresholds for testing
  min_non_zero_bytes: 10
  
  # Timeouts suitable for unit testing (shorter)
  connection_timeout_ms: 1000
  upstream_timeout_ms: 500

# Test parameters for different scenarios
test_scenarios:
  basic:
    width: 640
    height: 480
    fps: 30
    
  hd:
    width: 1280
    height: 720
    fps: 30
    
  full_hd:
    width: 1920
    height: 1080
    fps: 60
    
  low_fps:
    width: 640
    height: 480
    fps: 1
    
  high_fps:
    width: 640
    height: 480
    fps: 120
