#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Pulls the holohub CLI from the holohub repo
# The script checks if utilities/cli exists in the current directory,
# if not it pulls the holohub CLI from the holohub repo
# To update the holohub CLI, remove the utilities/cli directory and run the script again
if [ ! -d "${SCRIPT_PATH}/utilities/cli" ]; then
    git clone --depth 1 --no-checkout https://github.com/nvidia-holoscan/holohub.git ${SCRIPT_PATH}/.tmp-holohub/holohub \
        && cd ${SCRIPT_PATH}/.tmp-holohub/holohub \
        && git sparse-checkout init --cone \
        && git sparse-checkout set utilities/cli utilities/metadata utilities/testing utilities/setup cmake\
        && git checkout main \
        && mv ${SCRIPT_PATH}/.tmp-holohub/holohub/utilities ${SCRIPT_PATH} \
        && mv ${SCRIPT_PATH}/.tmp-holohub/holohub/cmake ${SCRIPT_PATH} \
        && rm -rf ${SCRIPT_PATH}/.tmp-holohub \
        && cd ${SCRIPT_PATH}
fi

export HOLOHUB_CMD_NAME=${BASH_SOURCE[0]}

PYTHONPATH=${PYTHONPATH}:${SCRIPT_PATH} python3 ${SCRIPT_PATH}/utilities/cli/holohub.py "$@"
