# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Golden Frame Testing Configuration for StreamingClientOp Enhanced
# This configuration is used for regression testing with golden reference frames

# Video settings (matching golden frame generation)
width: 854
height: 480
fps: 30

# Network settings (test configuration)
server_ip: "127.0.0.1"
signaling_port: 48010

# Frame handling for testing
receive_frames: false  # Disable for unit testing
send_frames: false     # Disable for unit testing

# Validation settings
min_non_zero_bytes: 100

# Test-specific settings
golden_frame_dir: "./golden_frames"
tolerance: 0.05  # 5% tolerance for frame comparison
max_test_frames: 10
