%YAML 1.2
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
scheduler:
  check_recession_period_ms: 0
  worker_thread_number: 5
  stop_on_deadlock: true
  stop_on_deadlock_timeout: 500
  # max_duration_ms: 20000

advanced_network:
  cfg:
    version: 1
    manager: "dpdk"
    master_core: 3
    debug: false
    log_level: "info"

    memory_regions:
    - name: "Data_RX_GPU1"
      kind: "device"
      affinity: 0
      num_bufs: 51200
      buf_size: 1064
    - name: "Data_RX_GPU2"
      kind: "device"
      affinity: 0
      num_bufs: 51200
      buf_size: 1064

    interfaces:
    - name: "rx_port"
      address: <0000:00:00.0>       # The BUS address of the interface doing Rx
      rx:
        flow_isolation: true
        queues:
        - name: "rx_q_0"
          id: 0
          cpu_core: 9
          batch_size: 10240
          memory_regions:
            - "Data_RX_GPU1"
        - name: "rx_q_1"
          id: 1
          cpu_core: 9
          batch_size: 10240
          memory_regions:
            - "Data_RX_GPU2"
        flows:
        - name: "flow_4096"
          id: 0
          action:
            type: queue
            id: 0
          match:
            udp_src: 4096
            udp_dst: 4096
        - name: "flow_4095"
          id: 1
          action:
            type: queue
            id: 1
          match:
            udp_src: 4095
            udp_dst: 4095

bench_rx:
  interface_name: "rx_port" # Name of the RX port from the advanced_network config
  gpu_direct: true          # Set to true if using a GPU region for the Rx queues.
  split_boundary: false     # Whether header and data is split (Header to CPU)
  batch_size: 10240
  max_packet_size: 1064
  header_size: 64
