name: Check links

on:
  push:
    branches: [main]
  pull_request:
jobs:
  link-check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v4
    - name: Link checker
      id: lychee
      uses: lycheeverse/lychee-action@v2
      with:
        workingDirectory: .github/workflows
        args: >-
          --accept=200,403,429
          --verbose
          --no-progress
          '${{ github.workspace }}/**/*.md'
          '${{ github.workspace }}/**/*.html'
          '${{ github.workspace }}/**/*.rst'
        fail: true
        jobSummary: true
