name: Check Docker

on:
  pull_request:
    branches: [main, holoscan-sdk-lws2]
  push:
    branches: [main, holoscan-sdk-lws2]

permissions:
  contents: read

jobs:
  check-docker-build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            ubuntu_version: 22.04
          - runner: ubuntu-24.04
            ubuntu_version: 24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Docker build
        run: |
          export ubuntu_version=${{ matrix.ubuntu_version }}

          ./holohub build-container --base-img ubuntu:${ubuntu_version}
