name: Check Compliance

on:
  push:
    branches: [main]
  pull_request:

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check copyright headers (PR - changed files only)
      if: github.event_name == 'pull_request'
      run: |
        echo "Checking copyright headers in changed files..."
        python3 .github/workflows/scripts/check_copyright.py --git-modified-only origin/${{ github.base_ref }} \
          --exclude-config .github/workflows/scripts/copyright_excludes.txt
        # full check: python3 .github/workflows/scripts/check_copyright.py --exclude-config .github/workflows/scripts/copyright_excludes.txt .


    - name: Check for internal artifacts
      run: |
        .github/workflows/scripts/check_nvstaging.sh \
          --exclude-config .github/workflows/scripts/nvstaging_excludes.txt \
          .
