name: Generate github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'github.io'
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clone HoloHub Repository (Latest)
        run: git clone https://github.com/nvidia-holoscan/holohub

      - name: Run gather.py
        shell: bash
        run: |
          cd holohub
          python ./utilities/gather_metadata.py --output aggregate_metadata.json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Move aggregate_metadata.json
        run: mv holohub/aggregate_metadata.json dist/

      - name: Stage dist folder
        run: git add dist -f

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update dist folder"

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
